Repository MrBSmith/XionLeak, pull requests merged in 2021-06, with the labels that each got.

#658 pushbutton should now work
  Scenes/InteractiveObjects/Buttons&Doors/Buttons/PushButton/PushButton.tscn
  Scenes/Levels/Chapter1/Level1.tscn
  Scenes/Levels/Chapter1/Level3.tscn
  Scenes/Levels/Debug/LevelDebug.tscn
  project.godot
Labels: Bug

#673 Fix save wrong location Fix #672
  Global/Autoloads/Game/Game.gd
  Scenes/Menus/SaveLoadMenus/SaveConfirmMenu/SaveConfirmMenu.gd
  default_settings.cfg
Labels: Bug, Priority

#675 Fix #642 platform slowly falling
  Scenes/Actor/ActorBase.gd
  Scenes/Actor/Platforms/MovingPlatforms/Flying/FlyingPlatform.gd
  Scenes/Actor/Platforms/MovingPlatforms/Flying/FlyingPlatform.tscn
  Scenes/Actor/Platforms/MovingPlatforms/MovingPlatform.gd
  Scenes/Actor/Platforms/RobotPlatformBase/RobotPlatformBase.gd
  Scenes/Actor/Robot/States/RobotJumpState.gd
  Scenes/InteractiveObjects/BreakableObjects/Blocks/IceBlock/S/IceBlockBase.gd
  Scenes/Levels/Debug/LevelDebug.tscn
  project.godot
Labels: Bug, Priority

#677 Fix #660
  Scenes/WorldMap/XL_WorldMap.tscn
  addons/WorldMapEditor/WorldMapEditor.gd
Labels: Enhancement, Priority
